<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="5" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-15T19:01:09 IST" name="Surefire suite" finished-at="2023-02-15T19:01:33 IST" duration-ms="24099">
    <groups>
      <group name="Purchase">
        <method signature="SubmitOrderTests.submitOrder(java.util.HashMap)[pri:0, instance:shady.tests.SubmitOrderTests@79efed2d]" name="submitOrder" class="shady.tests.SubmitOrderTests"/>
      </group> <!-- Purchase -->
      <group name="errorValidation">
        <method signature="ErrorValidationTests.LoginErrorValidation()[pri:0, instance:shady.tests.ErrorValidationTests@65d6b83b]" name="LoginErrorValidation" class="shady.tests.ErrorValidationTests"/>
      </group> <!-- errorValidation -->
    </groups>
    <test started-at="2023-02-15T19:01:09 IST" name="Surefire test" finished-at="2023-02-15T19:01:33 IST" duration-ms="24099">
      <class name="shady.tests.SubmitOrderTests">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:shady.tests.SubmitOrderTests@79efed2d]" started-at="2023-02-15T19:01:18 IST" name="launchApplication" finished-at="2023-02-15T19:01:21 IST" duration-ms="2668" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:shady.tests.SubmitOrderTests@79efed2d]" started-at="2023-02-15T19:01:21 IST" name="submitOrder" data-provider="getData" finished-at="2023-02-15T19:01:24 IST" duration-ms="2858" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Qwerty2@, product=ZARA COAT 3, email=w@w.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:shady.tests.SubmitOrderTests@79efed2d]" started-at="2023-02-15T19:01:24 IST" name="tearDown" finished-at="2023-02-15T19:01:24 IST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:shady.tests.SubmitOrderTests@79efed2d]" started-at="2023-02-15T19:01:24 IST" name="launchApplication" finished-at="2023-02-15T19:01:26 IST" duration-ms="2599" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:shady.tests.SubmitOrderTests@79efed2d]" started-at="2023-02-15T19:01:26 IST" name="submitOrder" data-provider="getData" finished-at="2023-02-15T19:01:29 IST" duration-ms="2775" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Mememe2@, product=ADIDAS ORIGINAL, email=me@me.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:shady.tests.SubmitOrderTests@79efed2d]" started-at="2023-02-15T19:01:29 IST" name="tearDown" finished-at="2023-02-15T19:01:29 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:shady.tests.SubmitOrderTests@79efed2d]" started-at="2023-02-15T19:01:29 IST" name="launchApplication" finished-at="2023-02-15T19:01:32 IST" duration-ms="2922" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:shady.tests.SubmitOrderTests@79efed2d]" started-at="2023-02-15T19:01:32 IST" name="OrderHistoryTest" finished-at="2023-02-15T19:01:33 IST" depends-on-methods="shady.tests.SubmitOrderTests.submitOrder" duration-ms="389" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:shady.tests.SubmitOrderTests@79efed2d]" started-at="2023-02-15T19:01:33 IST" name="tearDown" finished-at="2023-02-15T19:01:33 IST" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- shady.tests.SubmitOrderTests -->
      <class name="shady.tests.ErrorValidationTests">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:shady.tests.ErrorValidationTests@65d6b83b]" started-at="2023-02-15T19:01:09 IST" name="launchApplication" finished-at="2023-02-15T19:01:14 IST" duration-ms="5837" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:shady.tests.ErrorValidationTests@65d6b83b]" started-at="2023-02-15T19:01:14 IST" name="LoginErrorValidation" finished-at="2023-02-15T19:01:15 IST" duration-ms="286" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect emailll or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect emailll or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at shady.tests.ErrorValidationTests.LoginErrorValidation(ErrorValidationTests.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:shady.tests.ErrorValidationTests@65d6b83b]" started-at="2023-02-15T19:01:15 IST" name="tearDown" finished-at="2023-02-15T19:01:15 IST" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:shady.tests.ErrorValidationTests@65d6b83b]" started-at="2023-02-15T19:01:15 IST" name="launchApplication" finished-at="2023-02-15T19:01:17 IST" duration-ms="2801" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:shady.tests.ErrorValidationTests@65d6b83b]" started-at="2023-02-15T19:01:17 IST" name="LoginErrorValidation" finished-at="2023-02-15T19:01:18 IST" duration-ms="722" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect emailll or password.] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect emailll or password.] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at shady.tests.ErrorValidationTests.LoginErrorValidation(ErrorValidationTests.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:shady.tests.ErrorValidationTests@65d6b83b]" started-at="2023-02-15T19:01:18 IST" name="tearDown" finished-at="2023-02-15T19:01:18 IST" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- shady.tests.ErrorValidationTests -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
